apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-management
  labels:
    app: transaction-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transaction-management
  template:
    metadata:
      labels:
        app: transaction-management
    spec:
      containers:
        - name: transaction-management
          image: transaction_management:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"