apiVersion: v1
kind: Service
metadata:
  name: transaction_management_service
spec:
  selector:
    app: transaction_management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer